### ISSUE TITLE
Undefined class constant TYPE_LINK

### ISSUE THREAD

**Issue by dronmaxman** [rookie0/nextcloud-sharing-path#20]
Debian 9
PHP 7.3.9
NextCloud 16.0.1.1
sharing-path 0.2.2

Everything worked well and then everything broke.

When I try open shared link, I got error 

Error: Undefined class constant 'TYPE_LINK'
/var/www/nextcloud/apps/sharingpath/lib/Controller/PathController.php - line 85:

OCA\SharingPath\Controller\PathController->isShared("Andrey.Kurochkin", "m3u_iptv/Ukraine.m3u")

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OCA\SharingPath\Controller\PathController->handle("Andrey.Kurochkin", "m3u_iptv/Ukraine.m3u")

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OCA\SharingP ... {}, "handle")

/var/www/nextcloud/lib/private/AppFramework/App.php - line 126:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\SharingP ... {}, "handle")

/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("PathController", "handle", OC\AppFramew ... {}, { uid: "Andr ... "})

<<closure>>

OC\AppFramework\Routing\RouteActionHandler->__invoke({ uid: "Andr ... "})

/var/www/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { uid: "Andr ... "})

/var/www/nextcloud/lib/base.php - line 977:

OC\Route\Router->match("/apps/shari ... u")

/var/www/nextcloud/index.php - line 42:

OC::handleRequest()

**Comment by rookie0** [comment]
Sorry, my bad, because the change of constant use at [PathController.php#L164](https://github.com/rookie0/nextcloud-sharing-path/blob/master/lib/Controller/PathController.php#L164).

Affected versions [0.2.1 & 0.2.2](https://github.com/nextcloud/server/blob/master/lib/public/Share/IShare.php#L65).

You can temporary replace the code `IShare::TYPE_LINK` to `3` at `/your-nextcloud-install-path/apps/sharingpath/lib/Controller/PathController.php` line 164, or upgrade your nextcloud version greater than 17.0.0.
